# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_stubs import card_pb2 as grpc__stubs_dot_card__pb2


class CardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCardStock = channel.unary_stream(
                '/cards.CardService/GetCardStock',
                request_serializer=grpc__stubs_dot_card__pb2.Card_Request.SerializeToString,
                response_deserializer=grpc__stubs_dot_card__pb2.Card_Response.FromString,
                )


class CardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCardStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCardStock': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCardStock,
                    request_deserializer=grpc__stubs_dot_card__pb2.Card_Request.FromString,
                    response_serializer=grpc__stubs_dot_card__pb2.Card_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cards.CardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCardStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cards.CardService/GetCardStock',
            grpc__stubs_dot_card__pb2.Card_Request.SerializeToString,
            grpc__stubs_dot_card__pb2.Card_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
